name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}

      - name: Upload assets to release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.zip
            dist/*_SHA256SUMS*
          tag_name: ${{ github.ref_name }}
          name: AlertOps Terraform Provider ${{ github.ref_name }}
          body: |
            ## AlertOps Terraform Provider ${{ github.ref_name }}
            
            ### Installation
            
            #### Terraform Registry (Recommended)
            ```hcl
            terraform {
              required_providers {
                alertops = {
                  source  = "alertops/alertops"
                  version = "~> ${{ github.ref_name }}"
                }
              }
            }
            ```
            
            #### Manual Installation
            1. Download the appropriate binary for your platform from the Assets section below
            2. Extract the binary and place it in your Terraform plugins directory
            3. See [Installation Guide](https://github.com/alertops/terraform-provider-alertops#installation) for detailed instructions
            
            ### Documentation
            - [Provider Documentation](https://registry.terraform.io/providers/alertops/alertops/latest/docs)
            - [Examples](https://github.com/alertops/terraform-provider-alertops/tree/main/examples)
            - [Changelog](https://github.com/alertops/terraform-provider-alertops/blob/main/CHANGELOG.md)
            
            ### Support
            - 📧 [Support Email](mailto:support@alertops.com)
            - 🐛 [Report Issues](https://github.com/alertops/terraform-provider-alertops/issues)
            - 📖 [Documentation](https://docs.alertops.com)
          draft: false
          prerelease: false 